AOSC-Dev/autobuild3

arch/mips64el.sh

- This is not a platform-specific flag, and should not be placed here.
- '-fprefetch-loop-arrays' is a hard optimization -- it might be opened on
*some* softwares operating huge arrays, like databases, but not the
whole system.

arch/mips64el: remove -fprefetch-loop-arrays

---

etc/autobuild/ab3_defcfg.sh

We do MIPS64el (little-endian) port.

ab3_defcfg: add mips64el port

---

arch/amd64_avx2+.sh

Removing RDRND lets us support all the AVX2 CPUs in the setting. See https://sourceware.org/bugzilla/show_bug.cgi?id=23249#c12.
The question is... how important is RDRND for us anyways? Does GCC produce it without using intrinsics?

amd64_avx2: remove rdrnd

---

arch/_common.sh
arch/loongarch64.sh

autobuild3: initial adaptation for loongarch64 port; #119 
- tentative loongarch64 GCC compile flags and toolchain placeholder
- add arch/loongarch64.sh
- update arch/_common.sh to invoke toolchain placeholder
- delete meaningless mfix-loongson3-llsc flag for loongarch

draft for loongarch64

---

arch/_common.sh
arch/alpha.sh

This change introduces initial support for DEC Alpha-based systems to AutoBuild3.

Arch config for DEC Alpha-based systems.

---

lib/builtins.sh

When one of *.{diff,patch} not exists, a arg like *.diff or *.patch will pass in, that cause patch failure.

lib/buildins.sh: drop wrong input filename

---

lib/elf.sh

... so that new ELFs are recognized by the ELF filters.
GCC 11 starts to produce executables with type in header set to  "DYN (Position-Independent Executable file)" instead of the expected "EXEC (Executable file)".
When a ELF falls through the filter, AB3 produces a warning just in case other formats show up that we don't currently handle.

lib/elf: weaken constraints on DYN ELF types

---

arch/loongarch64.sh
arch/loongson2f.sh
arch/loongson3.sh
arch/powerpc.sh
arch/ppc64.sh
build/15-gomod.sh
etc/autobuild/ab3_defcfg.sh

In recent aosc-os-abbs topic [Go-1.18-survey-20220401](https://github.com/AOSC-Dev/aosc-os-abbs/pull/3923) , it is found that similar GOFLAGS is defined repeatably, making build script harder to read. This pull request attempt to resolve aforementioned issue and may make further packaging for go-based project easilier.
File changes: 
- `etc/autobuild/ab3_defcfg.sh`: set default `GOFLAGS`
- `arch/loongson3.sh`: disable go's `-buildmode=pie`
- `build/15-gomod.sh`: remove redundant check and codepath for loongson3

meta: introduce default GOFLAGS definition

---

qa/post/permissions.sh

The PR will fix a problem that when running `qa/post/permission.sh`. An example is that in the post-build QA phase of building `ocaml-ctypes` 0.16.0, autobuild3 will mistakenly treat some `*.so.owner` ASCII text file as shared object and fail the test. 
Commit 93f7388a will add a check command to determine whether the file is an ELF shared object or something else. 
The commit is tested via a dummy test package.
```
VER=1
DUMMYSRC=1
```
```
PKGNAME=testpkg
PKGDESC="Test package"
PKGSEC=admin
```
```
mkdir -vp $PKGDIR/usr/lib
cp -v /usr/lib/libffi.so $PKGDIR/usr/lib/THIS_SHOULD_FAIL.so.1
cp -v /usr/lib/libffi.so $PKGDIR/usr/lib/THIS_SHOULD_FAIL_TOO.so.2
echo "Never gonna give you up~" > $PKGDIR/usr/lib/BUT_THIS_SHOULD_NOT_FAIL.so.owner
chmod -x $PKGDIR/usr/lib/THIS_SHOULD_FAIL*
``` …

qa/post/permission.sh: add file type check for *.so.*

---

build/10-autotools.sh
build/11-cmakeninja.sh
build/12-cmake.sh
build/12-meson.sh
lib/base.sh

Currentlys AB3 couldn't handle parameter passing to cmake / autotools / meson for options that contain literal space characters due to `<build_type>_AFTER` being a single string. As a result bash cannot possibly distinguish a literal space apart from inter-field separators that splits the string into `char**`. AOSC maintainers usually resort to writing custom build scripts whenever these cases arises... which isn't great for consistency.
This PR adds support to use bash array for values of `CMAKE_AFTER`, `AUTOTOOLS_AFTER` and `MESON_AFTER`. Any options that should contain literal spaces can be specified as following:
```
CMAKE_AFTER=(
"-DOPTION_NAME=This is a literal sentence"
"-DQUOTED_OPTION=QuotedValue"
-DUNQUOTED_OPTION=Value
)
```
Existing `<build_type>_AFTER` as a huge string is …

`<build_type>_AFTER` declared as an array in defines

---

build/00-self.sh
etc/autobuild/ab3_defcfg.sh
proc/10-core_defines.sh
proc/40-patch.sh
proc/50-build_exec.sh
scriptlet/01-alternatives.sh

This pull request introduces support for Autobuild3 to read from `.stage2` (minimal/bootstrapping) recipes. Enable this mode by adding `ABSTAGE2=1` to `ab3cfg.sh`.
ACBS and Ciel has each introduced support to adapt to this change.

meta: introduce .stage2 suffix support

---

arch/_common.sh
arch/mips64r6el.sh

This is a change from the AOSC-CIP-Pilot project, which maintains AOSC OS' `mips64r6el` port, until it's deem ready for upstreaming to AOSC-Dev. This tooling change introduces `mips64r6el` architecture definitions.
- Triplet: `mips64r6el-aosc-linux-gnuabi64`
- Default C/C++ compiler flags: `-march=mips64r6 -mtune=mips64r6 -mcompact-branches=always`
- Default Rust target: `-Ctarget-cpu=mips64r6`

arch: introduce mips64r6el support

---

lib/arch.sh
lib/base.sh

autobuild3 allows maintainers to specify one or more `VARIABLE__AMD64` (by archtecture) and `VARIABLE__RETRO` (by arch group). These variables will override `VARIABLE` if the current building arch matches the more specific flags.
Earlier in #130 support is added to allow variables (e.g. `CMAKE_AFTER`) to be defined as a bash indexed array. However, at this point overriding `CMAKE_AFTER`-as-an-array with a literal `CMAKE_AFTER__ARM64` or the other way around is messed up and let's say undefined behavior.
This PR adds a short hand `abcopyvar` that enforces identical types for source and destination variables when copy-assigning, and causes build to fail if types don't match, i.e. when VAR_AMD64 is an array but VAR is a string literal, or when VAR_AMD64 is a string literal but VAR is an …

lib/arch, lib/base: Enforce type checking during copy-assigning (#140)

---

arch/mips64r6el.sh

This PR does the following two things:
- It sets `-Cdebuginfo=0` for rustc compiler. It enables rustc to build programs on mips64r6el, overriding all project configuration and build profile settings. Debug information just makes LLVM crash, not only on rustc, also Clang.
- It sets `--cfg=rustix_use_libc` for rustc compiler. This is on purpose because a crate named `rustix` has mips64r2 assembly written in it, but rustix itself can not distinguish between mips64r2 and mips64r6. Enabling config `rustix_use_libc` tells rustix to use underlying libc backend instead.

mips64r6el: apply Rust workarounds

---

filter/mancompress.sh

We could also decompress it (with `bsdtar` to save on `case`?), but the benefit is marginal at best. Just keep them as is.

mancompress: skip already compressed

---

filter/infocompress.sh
filter/mancompress.sh

xz(1) suggests using pb=0 for general English text. https://bugs.gentoo.org/169260#c19 shows that doing so cuts 1/3 from the compressed size, which is big. 
But do note that man-db search is awful slow for non-gz compression because of all the pipework involved. gz used to be slow to, until man-db started doing zlib decompress. See uhhh... somewhere around https://lore.kernel.org/linux-man/44768e26-ed92-0562-2318-68fec781126b@gmail.com/T/#m25978be2ce8245c67773911dbeb33140604e6d77.
Oh and xz without pb=0 doesn't provide much more compression than gzip -9, which is very normal given the tiny files. Maybe we should just go for gz.

mancompress: use pb=0 special sauce

---

build/15-rust.sh

cargo-audit 0.18 use rustls, break non amd64 and arm64 architectures

build/15-rust: do not run audit in non amd64 and arm64 arch

---

etc/autobuild/ab3_defcfg.sh
proc/11-pm_deps.sh

Introducing new variable `BUILDDEPONLY`.
In `autobuild/defines`, if `BUILDDEPONLY` is set to `1`, the flattened list of dependencies will not include `PKGDEP`. Therefore, Autobuil3 will not install the runtime dependencies when building.

Feature: BUILDDEPONLY

---

arch/amd64_avx+.sh
arch/amd64_avx2+.sh
arch/i386.sh
arch/loongson2f.sh
arch/powerpc.sh
arch/ppc64.sh

Just in case yall start yelling at me:
* `-mhle` never breaks anything.
* `-C target-feature=-altivec` turns OFF altivec. A plus sign turns it on.

Flags changes (arch)

---

etc/autobuild/ab3_defcfg.sh
pm/dpkg/pack
proc/10-tests_scan.sh
proc/31-tests_probe.sh

- No more junk logs
- Set NOTEST by default
- More information in the dpkg control file
- Remove unnecessary testing probe for NOTEST builds

Testing: better handling for NOTEST=yes
